_BASE_: "Base-SparseInst.yaml"
MODEL:
  WEIGHTS: "pretrained_models/R-50.pkl"
  SPARSE_INST:
    DECODER:
      NAME: "GroupIAMSoftDecoder"
SOLVER:
  AMP:
    ENABLED: True
OUTPUT_DIR: "output/sparse_inst_r50_giam_soft"